# Generated by Django 3.2.9 on 2021-12-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('customer_name', models.CharField(max_length=32, verbose_name='顾客名')),
                ('number', models.IntegerField(default=0, verbose_name='购买数量')),
                ('addr', models.CharField(max_length=254, verbose_name='顾客地址')),
                ('mobile', models.BigIntegerField(blank='True', verbose_name='手机')),
            ],
        ),
    ]
