# Generated by Django 3.2.9 on 2021-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.IntegerField(default=1000, verbose_name='库存'),
        ),
    ]
