# Generated by Django 3.2.9 on 2021-12-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_book_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='book_name',
            field=models.CharField(max_length=32, null=True, verbose_name='书名'),
        ),
    ]
